name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  lint-type-check:
    name: Lint & Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - run: npx prisma generate
      - run: npm run lint
      - run: npm run type-check

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://byteverse:testpassword@localhost:5432/byteverse_test
      REDIS_URL: redis://localhost:6379
      NEXTAUTH_SECRET: test-secret-for-ci-minimum-32-chars-long
      NEXTAUTH_URL: http://localhost:3000
      JUDGE0_URL: http://localhost:2358
      JUDGE0_WEBHOOK_SECRET: test-webhook-secret-min-32-chars-long
      AI_API_KEYS: sk-dummy
      AI_BASE_URL: https://api.groq.com/openai/v1
      AI_MODEL: llama-3.1-8b-instant
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: byteverse_test
          POSTGRES_USER: byteverse
          POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - run: npx prisma generate
      - run: npm test -- --passWithNoTests

  build:
    name: Production Build
    runs-on: ubuntu-latest
    needs: [lint-type-check, test]
    env:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: build-secret-for-ci-minimum-32-chars-long
      DATABASE_URL: postgresql://byteverse:password@localhost:5432/byteverse
      REDIS_URL: redis://localhost:6379
      JUDGE0_URL: http://localhost:2358
      JUDGE0_WEBHOOK_SECRET: build-webhook-secret-min-32-chars-long
      AI_API_KEYS: sk-dummy
      AI_BASE_URL: https://api.groq.com/openai/v1
      AI_MODEL: llama-3.1-8b-instant
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - run: npx prisma generate
      - run: npm run build
